---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: test
    image: docker.io/library/node:lts
    commands:
      - npm ci
      - npm test
